---
- name:       Check if JumpCloud folder exists
  stat:
    path:     "{{ jumpcloud_directory }}"
  register:   jumpcloud_directory_stat

- name:       Determine if JumpCloud is already installed
  set_fact:
    jc_installed: "{{ (jumpcloud_directory_stat.stat.isdir is defined and jumpcloud_directory_stat.stat.isdir) }}"

- name:       Install JumpCloud if required
  include:    install.yml
  when:       jc_installed != true or jumpcloud_force_install

...
