---
- name: Check if JumpCloud is already installed
  stat:
    path: "{{ jumpcloud_directory }}"
  register: jc_installed

- name:   Update time
  command:  'ntpdate -u pool.ntp.org'
  when: not jc_installed.stat.isdir || jumpcloud_force_install

- name: Install JumpCloud
  shell: "curl --header 'x-connect-key: {{ jumpcloud_x_connect_key | mandatory }}' {{ jumpcloud_x_connect_url | mandatory }} | sudo bash"
  when: not jc_installed.stat.isdir || jumpcloud_force_install
  notify:
    - restart JumpCloud
...
